---
- name: Deploy application
  hosts: production
  become: yes
  vars:
    container_name: "{{ project_name }}"
    
  tasks:
    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}
      
    - name: Stop existing container
      shell: |
        docker stop {{ container_name }} || true
        docker rm {{ container_name }} || true
      ignore_errors: yes
      
    - name: Pull latest image
      shell: |
        docker pull {{ ecr_registry }}/{{ project_name }}:{{ image_tag }}
        
    - name: Run new container
      shell: |
        docker run -d --name {{ container_name }} -p 8080:8080 \
          -e SPRING_PROFILES_ACTIVE=production \
          -e PROJECT_NAME={{ project_name }} \
          -e AWS_REGION={{ aws_region }} \
          --restart unless-stopped \
          {{ ecr_registry }}/{{ project_name }}:{{ image_tag }}
          
    - name: Verify container is running
      shell: docker ps | grep {{ container_name }}
      register: container_status
      
    - name: Show container status
      debug:
        msg: "Container {{ container_name }} is running: {{ container_status.stdout }}"