---
- name: Deploy application
  hosts: production
  become: yes
  vars:
    container_name: "{{ project_name }}"
    
  tasks:
    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}
      
    - name: Stop existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes
      
    - name: Pull latest image
      docker_image:
        name: "{{ ecr_registry }}/{{ project_name }}:{{ image_tag }}"
        source: pull
        
    - name: Run new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ ecr_registry }}/{{ project_name }}:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
        env:
          SPRING_PROFILES_ACTIVE: production
          PROJECT_NAME: "{{ project_name }}"
          AWS_REGION: "{{ aws_region }}"